deployment:
  tasks:
    - export DEPLOYPATH=/home/manasikt/public_html/
    - /bin/cp -r dist/public $DEPLOYPATH
    - /bin/cp dist/index.js $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/echo "Deployment complete"
